export const SUCCESS_USER_AUTHENTICATION = 'SUCCESS_USER_AUTHENTICATION';
export const USER_LOGOUT = 'USER_LOGOUT';

export const AUTH_MODAL_OPEN = 'AUTH_MODAL_OPEN';
export const MATCH_MODAL_OPEN = 'MATCH_MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const FIND_MATCH_PARTNER = 'FIND_MATCH_PARTNER';
export const SEND_MATCH_INVITATION = 'SEND_MATCH_INVITATION';
export const PENDING_MATCH_ACCEPTANCE = 'PENDING_MATCH_ACCEPTANCE';

export const RECEIVING_MATCH_INVITATION = 'RECEIVING_MATCH_INVITATION';
export const ACCEPT_MATCH_INVITATION = 'ACCEPT_MATCH_INVITATION';
export const REFUSE_MATCH_INVITATION = 'REFUSE_MATCH_INVITATION';

export const MATCH_PARTNER_ENTERED = 'MATCH_PARTNER_ENTERED';
export const MATCH_PARTNER_UNAVAILABLE = 'MATCH_PARTNER_UNAVAILABLE';
export const MATCH_PARTNER_REFUSE_MATCH_INVITATION = 'MATCH_PARTNER_REFUSE_MATCH_INVITATION';
export const FIND_MATCH_PARTNER_END = 'FIND_MATCH_PARTNER_END';

export const MATCH_PREPARATION = 'MATCH_PREPARATION';
export const MATCH_STARTED = 'MATCH_STARTED';
export const MATCH_PROBLEM_FETCHED = 'MATCH_PROBLEM_FETCHED';

export const MATCH_PARTNER_KEY_DOWN = 'MATCH_PARTNER_KEY_DOWN';
export const MATCH_PARTNER_KEY_UP = 'MATCH_PARTNER_KEY_UP';

export const MATCH_PARTNER_SOLUTION_SUBMITTED = 'MATCH_PARTNER_SOLUTION_SUBMITTED';
export const SOLUTION_SUBMITTED = 'SOLUTION_SUBMITTED';

export const CODE_CHANGED = 'CODE_CHANGED';
