export const AUTH = 'AUTH';
export const MATCH = 'MATCH';

export const APP_STAGE_FIND_MATCH_PARTNER = 'APP_STAGE_FIND_MATCH_PARTNER';
export const APP_STAGE_PENDING_MATCH_ACCEPTANCE = 'APP_STAGE_PENDING_MATCH_ACCEPTANCE';
export const APP_STAGE_RECEIVING_MATCH_INVITATION = 'APP_STAGE_RECEIVING_MATCH_INVITATION';
export const APP_STAGE_MATCH_PARTNER_REFUSE_MATCH_INVITATION = 'APP_STAGE_MATCH_PARTNER_REFUSE_MATCH_INVITATION';
export const APP_STAGE_MATCH_PARTNER_UNAVAILABLE = 'APP_STAGE_MATCH_PARTNER_UNAVAILABLE';
export const APP_STAGE_REFUSE_MATCH_INVITATION = 'APP_STAGE_REFUSE_MATCH_INVITATION';
export const APP_STAGE_ACCEPT_MATCH_INVITATION = 'APP_STAGE_ACCEPT_MATCH_INVITATION';
export const APP_STAGE_MATCH_PREPARATION = 'APP_STAGE_MATCH_PREPARATION';
export const APP_STAGE_MATCH_PROBLEM_FETCHED = 'APP_STAGE_MATCH_PROBLEM_FETCHED';
export const APP_STAGE_MATCH_STARTED = 'APP_STAGE_MATCH_STARTED';
