export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FIND_MATCH_PARTNER = 'FIND_MATCH_PARTNER';
export const SEND_MATCH_INVITATION = 'SEND_MATCH_INVITATION';

export const PENDING_MATCH_ACCEPTANCE = 'PENDING_MATCH_ACCEPTANCE';
export const ACCEPT_MATCH_INVITATION = 'ACCEPT_MATCH_INVITATION';
export const REFUSE_MATCH_INVITATION = 'REFUSE_MATCH_INVITATION';
export const MATCH_PARTNER_ENTERED = 'MATCH_PARTNER_ENTERED';

export const MATCH_PARTNER_UNAVAILABLE = 'MATCH_PARTNER_UNAVAILABLE';
export const MATCH_PARTNER_REFUSE_MATCH_INVITATION = 'MATCH_PARTNER_REFUSE_MATCH_INVITATION';
