export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FIND_MATCH_PARTNER = 'FIND_MATCH_PARTNER';
export const SEND_MATCH_INVITATION = 'SEND_MATCH_INVITATION';

export const PENDING_MATCH_ACCEPTANCE = 'PENDING_MATCH_ACCEPTANCE';
export const ACCEPT_MATCH_INVITATION = 'ACCEPT_MATCH_INVITATION';
export const REFUSE_MATCH_INVITATION = 'REFUSE_MATCH_INVITATION';
export const MATCH_PARTNER_ENTERED = 'MATCH_PARTNER_ENTERED';

export const MATCH_PARTNER_UNAVAILABLE = 'MATCH_PARTNER_UNAVAILABLE';
export const MATCH_PARTNER_REFUSE_MATCH_INVITATION = 'MATCH_PARTNER_REFUSE_MATCH_INVITATION';
export const FIND_MATCH_PARTNER_END = 'FIND_MATCH_PARTNER_END';

export const SEND_RANDOM_PROBLEM = 'SEND_RANDOM_PROBLEM'
export const MATCH_START = 'MATCH_START';

export const MATCH_PARTNER_KEY_DOWN = 'MATCH_PARTNER_KEY_DOWN';
export const MATCH_PARTNER_KEY_UP = 'MATCH_PARTNER_KEY_UP';

export const KEY_UP = 'KEY_UP';
export const KEY_DOWN = 'KEY_DOWN';

export const MATCH_PARTNER_SUBMIT_SOLUTION = 'MATCH_PARTNER_SUBMIT_SOLUTION';
export const SUBMIT_SOLUTION = 'SUBMIT_SOLUTION';

export const MATCH_PARTNER_SOLUTION_SUBMITTED = 'MATCH_PARTNER_SOLUTION_SUBMITTED';
export const SOLUTION_SUBMITTED = 'SOLUTION_SUBMITTED';

export const MATCH_TIMER = 'MATCH_TIMER';
export const USER_WINNING = 'USER_WINNING';
export const MATCH_PARTNER_WINNING = 'MATCH_PARTNER_WINNING';
export const USER_GIVE_UP = 'USER_GIVE_UP';
export const MATCH_PARTNER_GIVE_UP = 'MATCH_PARTNER_GIVE_UP';

export const USER_SOCKET_INIT = 'USER_SOCKET_INIT';